# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# General
title: Navitia SDK
email: team.sdk@kisio.com
description: >- # this means to ignore newlines until "baseurl:"
  Documentation about SDK modules for Android and iOS
baseurl: "/navitia_sdk_docs" # the subpath of your site, e.g. /blog
url: "https://canaltp.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty
remote_theme: pmarsceill/just-the-docs
color_scheme: sdk

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Heading anchors
heading_anchors: true

# Footer
back_to_top: true
back_to_top_text: "Back to top"
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Build settings
incremental: true
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .jekyll-cache
