# Project information
site_name: Navitia SDK Docs
site_url: https://hove-io.github.io/navitia_sdk_docs/
site_author: Front Mobile Team
site_description: >-
  Create your own transport application using Navitia SDKs
  
# Repository
repo_name: hove-io/navitia_sdk_docs
repo_url: https://github.com/hove-io/navitia_sdk_docs

# Copyright
copyright: Copyright &copy; 2024 Hove
  
# Configuration
theme:
  name: material
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - search.share
    - toc.follow
  palette:
    - scheme: navitia-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/img/favicon.svg
  logo: assets/img/hove.svg

# Code snippets/tables/emojis
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - tables
  - toc:
      toc_depth: 4
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

# Social links/languages
extra:
  #generator: false // Hide the Made with Material MKDocs
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hove-io/navitia
    - icon: fontawesome/brands/medium
      link: https://navitia-io.medium.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hove_kdigital
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/kisiodigital
    - icon: fontawesome/solid/frog
      link: https://kisiodigital.jfrog.io/

# Page tree
nav:
  - Home: index.md
  - Getting started: getting_started.md
  - Around Me:
    - Android:
      - Documentation: around_me/android/index.md
      - Changelogs: around_me/android/changelogs.md
    - iOS:
      - Documentation: around_me/ios/index.md
      - Changelogs: around_me/ios/changelogs.md
    - Screens: around_me/screens/index.md
  - Bookmark:
    - Android:
      - Documentation: bookmark/android/index.md
      - Changelogs: bookmark/android/changelogs.md
    - iOS:
      - Documentation: bookmark/ios/index.md
      - Changelogs: bookmark/ios/changelogs.md
    - Screens: bookmark/screens/index.md
  - Expert:
    - Android:
      - Documentation: expert/android/index.md
      - APIs: expert/android/apis.md
      - Models: expert/android/models.md
      - Changelogs: expert/android/changelogs.md
    - iOS:
      - Documentation: expert/ios/index.md
      - APIs: expert/ios/apis.md
      - Models: expert/ios/models.md
      - Changelogs: expert/ios/changelogs.md
  - Journey:
    - Android:
      - Documentation: journey/android/index.md
      - Changelogs: journey/android/changelogs.md
    - iOS:
      - Documentation: journey/ios/index.md
      - Changelogs: journey/ios/changelogs.md
    - Screens: journey/screens/index.md
  - Schedule:
    - Android:
      - Documentation: schedule/android/index.md
      - Changelogs: schedule/android/changelogs.md
    - iOS:
      - Documentation: schedule/ios/index.md
      - Changelogs: schedule/ios/changelogs.md
    - Screens: schedule/screens/index.md
  - Traffic:
    - Android:
      - Documentation: traffic/android/index.md
      - Changelogs: traffic/android/changelogs.md
    - iOS:
      - Documentation: traffic/ios/index.md
      - Changelogs: traffic/ios/changelogs.md
    - Screens: traffic/screens/index.md
    
# Extra config
extra_css:
  - css/extra.css

# Hide edit button
edit_uri: ""

# Plugins
plugins:
  - search
  - exclude:
      glob:
        #- around_me/*
        #- bookmark/*
        #- expert/*
        #- journey/*
        #- schedule/*
        #- traffic/*
